FROM --platform=linux/amd64 jeffersonlab/gemc:dev-almalinux94

RUN curl -sL "https://clasweb.jlab.org/clas12offline/distribution/coatjava/coatjava-10.0.7.tar.gz" \
    | tar xz -C /opt \
 && echo 'export COATJAVA=/opt/coatjava' >> /etc/profile.d/coatjava.sh \
 && echo 'export PATH=$COATJAVA/bin:$PATH' >> /etc/profile.d/coatjava.sh
